#!/bin/bash

# execute this script after adding or removing a package

function joinArr {
  local IFS="$1";
  shift;
  echo "$*";
}

packages_dir="./packages"
list_file="./package_list"

files=( $(ls $packages_dir) )
list=$(joinArr , ${files[@]})

contents=$(printf "# do not manually edit this file
# this file is generated by scripts/rebuild_package_list.sh
$list")

function build {
  echo "$contents" > $list_file
  echo "Saved rebuilt package list to $list_file"
}

if [ -f "$list_file" ]; then
  if [[ $(< $list_file) == "$contents" ]]; then
    echo "Did not need to rebuild package list"
  else
    rm "$list_file"
    build
  fi
else
  build
fi
